= 命名

待整理

~~~

https://www.cnblogs.com/FlyAway2013/p/10166359.html[DO/BO/DTO/VO/AO/PO]

https://unbug.github.io/codelf[codelf 命名搜索神器]

切记, 要因地制宜, 实事求是, 根据当前情况判断如何使用, 而不陷入模式.

各种分层模型/命名规范 给出了很好的建议, 但并不一定适合所有状况.

~~~

.分层领域模型规约：
. DO（ Data Object）：与数据库表结构一一对应，通过DAO层向上传输数据源对象。
. DTO（ Data Transfer Object）：数据传输对象，Service或Manager向外传输的对象。
. BO（ Business Object）：业务对象。 由Service层输出的封装业务逻辑的对象。
. AO（ Application Object）：应用对象。 在Web层与Service层之间抽象的复用对象模型，极为贴近展示层，复用度不高。
. VO（ View Object）：显示层对象，通常是Web向模板渲染引擎层传输的对象。
. POJO（ Plain Ordinary Java Object）：在本手册中， POJO专指只有setter/getter/toString的简单类，包括DO/DTO/BO/VO等。
. Query：数据查询对象，各层接收上层的查询请求。 注意超过2个参数的查询封装，禁止使用Map类来传输。

.领域模型命名规约：
. 数据对象：xxxDO，xxx即为数据表名。
. 数据传输对象：xxxDTO，xxx为业务领域相关的名称。
. 展示对象：xxxVO，xxx一般为网页名称。
. POJO是DO/DTO/BO/VO的统称，禁止命名成xxxPOJO。

~~~

个人认为, 定义各种不同类型的结构体是为了实现更好的解耦的, 
从而实现当内部/外部需求变化时, 程序重构需要更小的代价.

一个项目至少要定义 VO 对象: XXView. 
用于Controller对外返回, 而不是直接使用数据库结构或者内部结构.

View对象强烈推荐使用. 因为需求变化后, 很难再改别的项目(调用本项目的项目)
的代码, 使用View可以更好的解耦.

~~~

一个Service领域, 一般至少要有如下三个类

. DTO 对象: XXTransfer. 该服务对外展示的对象, 包括服务返回, RPC调用该方法返回值等.
. DO 对象. XX 或 XXDO. 与数据库表结构对应, 用于存储.
. CreateXXRequest. 创建该数据需要的字段.

DTO 有两种定义时机.

. 开始开发时就定义. 
. 开始开发时不定义, 当出现需要 DTO 的需求时, 重构代码, 添加DTO. 惰性更新, 快速开发+迭代的方式.

~~~

bussiness/service 区别

分层是对业务的理解达到一定层级所必须了解的事, 跟设计模式一样, 
是前人总结的那些常犯的错误, 常用的模式, 避免后人再犯这些错误, 使用错误的结构.

business是业务层，他是常常变化的，所不定业务场景每天都在变，或者说他随时会被在平台系统中个摘下来，不再用了。而servicec层是一个并不常常变化的业务层面，他是一个稳定的板块，核心的，是无法摘掉的。

在软件工程的项目设计中，最理想的状态时把business做到一种可以插拔式的业务形态，而service就像一个主电源线。这也许是如今讨论的如火如荼的soa应用的初衷。

soa要把业务给拆分，主要是为了做到一下几点：

1）程序写着写着，发现项目每次发布项目上线、启动项目太慢了，以前是小程序的时候，上线和启动的时间2分钟，当程序变大了，就需要1-2个小时甚至更久。上线发布就成为了一个问题，这不得不到了给程序瘦身的地步（这是soa实现最明显的一点）；

2）知道要拆分系统，让他上线发布变的更快，但是，应该如何去拆分呢？这就是service与business的真正区别，**我们拆分系统应该要有一个主线，这就是service, serivice 一般会包含一个平台的基本功能的一些骨架，比如权限、用户、监控这写都是模块就是service的代码，他们在完成、并趋向稳定后基本不会有改动。business 的业务就像秒杀活动的业务、团购活动业务，这些都是一些business模块，他们可以对接到service的主干平台系统中，也可以在不玩什么推广活动，就能随时把他们卸载下**

像群点单中创建订单， 下单成功发送模板消息+shldf等信息的填充 是biz层，创建逻辑在service层。

docenter中, DocSvc是services层，虽然他是聚合其他服务的，自己并不存储，但是docSvc是稳定的，独立的基础业务逻辑。docSvc没有像biz层一样添加一些其他的业务逻辑，所以是svc层

所以，谨记，docSvx是svc层。写文章时把这个例子加上，这类文章多举例。理论太难懂了。

biz用bo结构体。

service 用 DTO 结构体

dao 用DO (目前是直接与名称对应了)

~~~

还需要注意的一个是，不要过早的优化。所以，一开始分层特别细也是不好的，因为会影响开发进度。还是采取迭代开发的方式，逐步迭代比较好。

快速开发+迭代演化 更好，不要过分追求模式和结构，从而影响进度。代码可以重构，但是deadline/时机不等人。所以，我推荐以快速开发，实现功能为主，然后需要需求时，通过迭代逐步完善架构的方式。

如docenter的开发，先实现各个功能，由于初版不需要biz层，也就不添加biz层了，直接 ctrl调用svc，完成功能快速上线。

后期如果有了创建文章后，自动推送消息的逻辑，则添加biz层，完成这个逻辑。成为迭代。

当然，如果写svc时，类似dto这种能随手能加上的，那就加上。毕竟有了更好，程序更健壮。但是类似biz需要专门去写的就算了，以进度为主，等有需求了再迭代开发，加上biz。

即惰性更新. 当然，如果时间比较充裕，要求比较严格, 那么当然要使用更好的架构, 结构也追求更完善。
