// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "xgxw.demo.Request")
	proto.RegisterType((*Response)(nil), "xgxw.demo.Response")
}

func init() { proto.RegisterFile("demo.proto", fileDescriptor_ca53982754088a9d) }

var fileDescriptor_ca53982754088a9d = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xc1, 0x6a, 0xc2, 0x40,
	0x10, 0x86, 0x9b, 0xad, 0x58, 0x9d, 0x40, 0x2b, 0xeb, 0x45, 0x72, 0x31, 0xd8, 0x8b, 0x94, 0x9a,
	0x40, 0x0b, 0x3e, 0x40, 0xb0, 0x97, 0x1e, 0xd7, 0x4b, 0xe9, 0x2d, 0x71, 0x87, 0x75, 0x49, 0x37,
	0x13, 0x77, 0x37, 0xc6, 0xb7, 0x15, 0x7c, 0x92, 0x62, 0x52, 0x84, 0xde, 0x7e, 0x3e, 0x66, 0xfe,
	0x99, 0x0f, 0x40, 0xa2, 0xa1, 0xa4, 0xb6, 0xe4, 0x89, 0x8f, 0x4f, 0xea, 0xd4, 0x26, 0x57, 0x10,
	0xad, 0x95, 0xf6, 0xfb, 0xa6, 0x48, 0x76, 0x64, 0x52, 0xd3, 0x6a, 0x5f, 0x52, 0x9b, 0x2a, 0x5a,
	0x75, 0x73, 0xab, 0x63, 0xfe, 0xa3, 0x65, 0xee, 0xc9, 0xba, 0xf4, 0x16, 0xfb, 0x8a, 0xc5, 0x27,
	0x3c, 0x08, 0x3c, 0x34, 0xe8, 0x3c, 0x7f, 0x06, 0xa6, 0xe5, 0x2c, 0x88, 0x83, 0xe5, 0x20, 0x9b,
	0x5e, 0xce, 0xf3, 0xa7, 0xc9, 0xdd, 0x4b, 0xa8, 0x65, 0x6c, 0xf1, 0xd0, 0x68, 0x8b, 0x52, 0x30,
	0x2d, 0x79, 0x04, 0x83, 0x2a, 0x37, 0x38, 0x63, 0x71, 0xb0, 0x1c, 0x67, 0xc3, 0xcb, 0x79, 0xce,
	0xbe, 0x02, 0xd1, 0xb1, 0xc5, 0x2b, 0x8c, 0x04, 0xba, 0x9a, 0x2a, 0x87, 0xfc, 0x11, 0x18, 0x95,
	0x5d, 0xd9, 0x48, 0x30, 0x2a, 0xf9, 0x04, 0xee, 0x8d, 0x53, 0xfd, 0x9a, 0xb8, 0xc6, 0xb7, 0x0f,
	0x08, 0x37, 0x68, 0x68, 0x8b, 0xf6, 0xa8, 0x77, 0xc8, 0xd7, 0x10, 0x6e, 0x68, 0x4b, 0x06, 0xfd,
	0x5e, 0x57, 0x8a, 0xf3, 0xe4, 0xe6, 0x96, 0xfc, 0x3d, 0x18, 0x4d, 0xff, 0xb1, 0xfe, 0x50, 0x36,
	0xf8, 0x66, 0x75, 0x51, 0x0c, 0x3b, 0x9b, 0xf7, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa8, 0xc1,
	0x30, 0x98, 0x1e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DemoServiceClient is the client API for DemoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DemoServiceClient interface {
	DoSomething(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type demoServiceClient struct {
	cc *grpc.ClientConn
}

func NewDemoServiceClient(cc *grpc.ClientConn) DemoServiceClient {
	return &demoServiceClient{cc}
}

func (c *demoServiceClient) DoSomething(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/xgxw.demo.DemoService/DoSomething", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DemoServiceServer is the server API for DemoService service.
type DemoServiceServer interface {
	DoSomething(context.Context, *Request) (*Response, error)
}

// UnimplementedDemoServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDemoServiceServer struct {
}

func (*UnimplementedDemoServiceServer) DoSomething(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoSomething not implemented")
}

func RegisterDemoServiceServer(s *grpc.Server, srv DemoServiceServer) {
	s.RegisterService(&_DemoService_serviceDesc, srv)
}

func _DemoService_DoSomething_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoServiceServer).DoSomething(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xgxw.demo.DemoService/DoSomething",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoServiceServer).DoSomething(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _DemoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "xgxw.demo.DemoService",
	HandlerType: (*DemoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoSomething",
			Handler:    _DemoService_DoSomething_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo.proto",
}
